---
name: validate

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  validate-legacy:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        # test every target we can easily do in ci
        os: ["ubuntu-latest", "macos-latest", "ubuntu-24.04-arm"]

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: set release version
        run: |
          RELEASE_TAG=${{ github.ref_name }}
          RELEASE_VERSION=${RELEASE_TAG#v}

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_ENV"

          PRERELEASE=${RELEASE_VERSION#*[0-9].[0-9].[0-9]}
          if [[ "$PRERELEASE" == "$RELEASE_VERSION" ]]; then
            PRERELEASE=""
          fi

          CALVER=$(date +'%Y.%m.%d')

          if [[ -n "$PRERELEASE" ]]; then
            CALVER="$CALVER$PRERELEASE"
          fi

          echo "CALENDAR_VERSION=$CALVER" >> "$GITHUB_ENV"

      - name: load env vars for workflow run
        run: |
          source .github/vars.env
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"

      - name: remove checkedout scrapli
        run: rm -rf scrapli

      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install scrapli and load ffi mapping
        run: |
          python -m pip install "scrapli==${{ env.CALENDAR_VERSION }}"
          python -c 'from scrapli.ffi_mapping import LibScrapliMapping; LibScrapliMapping()'

  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        # test every target we can easily do in ci
        os: ["ubuntu-latest", "macos-latest", "ubuntu-24.04-arm", "macos-13"]

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: set release version
        run: |
          RELEASE_TAG=${{ github.ref_name }}
          RELEASE_VERSION=${RELEASE_TAG#v}

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_ENV"

      - name: load env vars for workflow run
        run: |
          source .github/vars.env
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"

      - name: remove checkedout scrapli
        run: rm -rf scrapli

      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install scrapli and load ffi mapping
        run: |
          python -m pip install "scrapli2==${{ env.RELEASE_VERSION }}"
          python -c 'from scrapli.ffi_mapping import LibScrapliMapping; LibScrapliMapping()'
